refactor: cicd backend

diff --git a/.github/workflows/deploy-back.yml b/.github/workflows/deploy-back.yml
--- a/.github/workflows/deploy-back.yml
+++ b/.github/workflows/deploy-back.yml
@@ -8,9 +8,9 @@ on:
       - '.github/workflows/deploy-back.yml'
 
 env:
-  DEPLOY_PATH: /path
-  SERVER_DOMAIN: address
-  SERVER_USER: user
+  DEPLOY_PATH: /home/easyfund/backend
+  SERVER_DOMAIN: 147.45.147.73
+  SERVER_USER: root
 
 jobs:
   deploy_backend:
@@ -32,11 +32,11 @@ jobs:
       # Создание .env из base64-секрета
       - name: Create .env file
         run: |
-          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env
+          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env.prod
 
       # Сборка Docker-образа
       - name: Build Docker image
-        run: docker compose --env-file=.env build
+        run: docker compose --env-file=.env.prod build
 
       # Сохранение Docker-образа в tar-файл
       - name: Save Docker image
@@ -82,7 +82,7 @@ jobs:
             fi
             cd $DEPLOY_PATH
             docker load -i image.tar || { echo 'Failed to load Docker image'; exit 1; }
-            docker compose --env-file=.env up -d --force-recreate || { echo 'Failed to start containers'; exit 1; }
+            docker compose --env-file=.env.prod up -d --force-recreate || { echo 'Failed to start containers'; exit 1; }
             echo 'Deployed!'
           "
 
